### ISSUE TITLE
Stable channel should not have development builds

### ISSUE THREAD

**Issue by bitscuit** [alexmurray/golangci-lint-snap#5]
I installed golangci-lint in the stable channel

```
golangci-lint             1.60.1           265    latest/stable    alexmurray✪  classic
```

But there are 2 major issues with this package

1. This is using a development version of golangci-lint, which doesn't belong in a stable channel

```
$ golangci-lint version
golangci-lint has version (devel) built with go1.22.6 from (3298c104802d118670a487b330ddd3761f7afe20, modified: true, mod sum: "") on 2024-08-14T01:09:25Z
```

2. golangci-lint v1.60.1 is officially built with go v1.23.0, **NOT** with go v1.22.6 as shown in the version info. This is a major issue because it causes golangci-lint to crash when linting go 1.23.0 code as stated here https://github.com/golangci/golangci-lint-action/issues/1086#issuecomment-2297899939

**Comment by alexmurray** [comment]
So the `devel` part is misleading - the snap is built from source, not from the upstream binaries since this allows the snap to support other architectures that upstream is not supporting. As you can see in https://github.com/alexmurray/golangci-lint-snap/blob/master/snapcraft.yaml#L19 it builds from the 1.60.1 tag of golangci-lint upstream, but since it is building from a git checkout then it tags itself as `devel` - I might be able to try and workaround this to report the correct version but this is not really a high priority.

Regarding the version of go used, we use the latest stable version of the go snap (https://snapcraft.io/go) which at that time was 1.22.6 - I see this is now at 1.23 so have retriggered another build of the snap which should then use this new version of go. This should be available soon in the edge channel so if you can test it and let me know whether this works as expected with go 1.23.0 that would be great. Thanks.

**Comment by bitscuit** [comment]
Thanks will give this a try when I can.

On a related note, instead of using the latest stable version of go snap to build, shouldn't the go version match whatever upstream is using to build? Don't know how feasible that would be to automate

**Comment by alexmurray** [comment]
Hmm I am not sure how we would easily do that. But I think that is unrelated to this issue - feel free to open a separate issue though about this (ie. making sure the snap build of golangci-lint uses the latest version of go to compile).

**Comment by alexmurray** [comment]
(for posterity - the version number was fixed in https://github.com/alexmurray/golangci-lint-snap/commit/309f5692c453e6495865207d3f180e3e16e837e9)

**Comment by bitscuit** [comment]
Thank you

**Comment by bitscuit** [comment]
```
$ golangci-lint version
golangci-lint has version 1.60.3 built with go1.23.0 from c2e095c0 on 2024-08-22T23:20:15Z
```

Tried it, and it works with go 1.23.0 code, thanks
