### ISSUE TITLE
Official publishing of golangci-lint

### ISSUE THREAD

**Issue by ldez** [alexmurray/golangci-lint-snap#6]
Hello,

Thanks for your work on [this Snap](https://snapcraft.io/golangci-lint).

I'm a maintainer of golangci-lint, and we plan to integrate the publication of the snap into our release process.

https://github.com/golangci/golangci-lint/pull/5130

Could you transfer the ownership to me?

Snapcraft account: golangci
Snapcraft forum account: ldez

**Comment by alexmurray** [comment]
Thanks - yes I am happy to transfer it but we should go through the [publisher vetting process](https://forum.snapcraft.io/t/process-for-performing-snap-publisher-vetting/43531) as part of this since the snap has classic confinement granted to it already. Also ideally we would also get the publisher account [verified](https://forum.snapcraft.io/t/verified-accounts/34002) as well. Since you are already in the snapcraft forum, could you please create 2 new topics there for both of these requests, one for the snap transfer in the https://forum.snapcraft.io/c/store-requests/transfer-ownership/30 category, and the other for the account verification in the https://forum.snapcraft.io/c/policy/policy-requests/25 category? Thanks.

**Comment by ldez** [comment]
- https://forum.snapcraft.io/t/transfer-ownership-of-golangci-lint-snap/43977
- https://forum.snapcraft.io/t/publisher-vetting-golangci/43979

:thinking: To be verified the golangci account needs to have snap, but to get this snap I need to be a verified account. There is a loop :smile: 
Also, I am not sure if we meet the [criteria](https://forum.snapcraft.io/t/verified-accounts/34002).

**Comment by ldez** [comment]
The transfer process is done, thank you @alexmurray.
